StoreLedger/Pages/Sales/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreLedger.Model;
using StoreLedger.Model.Repos;
using StoreLedger.Models.ViewModels;

namespace StoreLedger.Pages.Sales
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly InventoryCategoryRepo _categoryRepo;
        private readonly InventoryRepo _inventoryRepo;

        public IndexModel(InventoryCategoryRepo categoryRepo, InventoryRepo inventoryRepo)
        {
            _categoryRepo = categoryRepo;
            _inventoryRepo = inventoryRepo;
            Categories = new List<InventoryCategory>();
            Inventories = new List<InventoryView>();
            //Sales = new List<InventorySaleViewModel>();
        }

        public List<InventoryCategory> Categories { get; set; }
        public List<InventoryView> Inventories { get; set; }
        public List<InventoryView> InventoriesForSale { get; set; }

        //[BindProperty]
        //public List<InventorySaleViewModel> Sales { get; set; }

        public async Task OnGetAsync()
        {
            Categories = await _categoryRepo.GetHavningInventory();
            Inventories = await _inventoryRepo.GetWithStock();
            InventoriesForSale = await _inventoryRepo.GetWithStockForSales();
        }

        //public async Task<IActionResult> OnPostSellAsync(List<SaleItemViewModel> sales)
        //{
        //    var saleitems = sales;


        //    //save to temp tr
        //    return RedirectToPage("./index");
        //}
    }
}

StoreLedger/Pages/Sales/Pay.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreLedger.Activities;
using StoreLedger.Model;
using StoreLedger.Model.Repos;
using StoreLedger.Models;
using StoreLedger.Models.ViewModels;

namespace StoreLedger.Pages.Sales
{
    [Authorize]
    public class PayModel : BasePageModel
    {
        private readonly InventoryCategoryRepo _categoryRepo;
        private readonly InventoryRepo _inventoryRepo;
        private readonly TransactionActivity _transActivity;

        public PayModel(InventoryCategoryRepo categoryRepo, InventoryRepo inventoryRepo, TransactionActivity transActivity)
        {
            _categoryRepo = categoryRepo;
            _inventoryRepo = inventoryRepo;
            _transActivity = transActivity;
            Categories = new List<InventoryCategory>();
            Inventories = new List<InventoryView>();
            //Sales = new List<InventorySaleViewModel>();
        }

        public List<InventoryCategory> Categories { get; set; }
        public List<InventoryView> Inventories { get; set; }

        //[BindProperty]
        public List<SaleItemViewModel> Sales { get; set; }

        public async Task OnGetAsync()
        {
            
        }

        public async Task<IActionResult> OnPostSellAsync(List<SaleItemViewModel> model)
        {
            if (!model.Any())
            {
                FlashError("Select items to sell");
                return RedirectToPage("./index");
            }
            var inventory = await _inventoryRepo.GetWithStock();
            if(!inventory.Any()) return RedirectToPage("./index");

            foreach (var item in model)
            {
                var currInventory = inventory.FirstOrDefault(c => c.InventoryId == item.InventoryId);
                if (currInventory == null) continue;
                item.Name = currInventory.Name;
                item.Code = currInventory.Code;
                item.Price = currInventory.Price;
                item.Total = item.Price * item.Quantity;
            }

            Sales = model;

            return Page();
        }

        public async Task<IActionResult> OnPostProcessTransactionAsync(SaleViewModel model)
        {
            var userId =
                Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == Defaults.UserType.Id)?.Value);
            var results = await _transActivity.ProcessTransaction(userId, model);
            if (results.IsSuccessful)
            {
                FlashSuccess("Payment completed successfully");
                return RedirectToPage("./index");
            }

            FlashError(results.Message);
            return Page();
        }
    }
}

StoreLedger/Pages/Sales/Receipts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreLedger.Model;
using StoreLedger.Model.Repos;

namespace StoreLedger.Pages.Sales
{
    [Authorize]
    public class ReceiptsModel : PageModel
    {
        private readonly TransactionRepo _transactionRepo;
        private readonly TransactionItemRepo _transactionItemRepo;
        private readonly InventoryRepo _inventoryRepo;
        private readonly UserRepo _userRepo;

        public List<TransactionItem> TransactionItems { get; set; }
        public List<Model.Inventory> Inventories { get; set; } 
        public DateTime CurrentDate { get; set; }
        public List<User> Users { get; set; }

        public ReceiptsModel(TransactionRepo transactionRepo, TransactionItemRepo transactionItemRepo, 
            InventoryRepo inventoryRepo, UserRepo userRepo)
        {
            _transactionRepo = transactionRepo;
            _transactionItemRepo = transactionItemRepo;
            _inventoryRepo = inventoryRepo;
            _userRepo = userRepo;

            TransactionItems = new List<TransactionItem>();
        }

        public async Task OnGetAsync(DateTime? currDate)
        {
            CurrentDate = currDate != null ?
                DateTime.Parse(currDate.ToString()) :
                DateTime.Today;

            TransactionItems = await _transactionItemRepo.GetDayReport(CurrentDate);
            Inventories = await _inventoryRepo.GetAllAsync();
            Users = await _userRepo.GetAllAsync();
        }
    }
}

StoreLedger/Pages/Sales/Pay.cshtml
@page
@using Newtonsoft.Json
@using StoreLedger.Model
@model StoreLedger.Pages.Sales.PayModel
@{
    ViewData["Title"] = "Sales: Pay";
    var subTotal = 0.0M;
}
@section scripts{
    <link href="/assets/plugins/select2/dist/css/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />
    <link href="/assets/plugins/multiselect/css/multi-select.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css" rel="stylesheet" />
}
@functions {

string GetColorClass(Random rand)
{
    var classes = new[] { "label-light-info", "label-stock", "label-light-primary", "label-light-danger" };

    return classes[rand.Next(0, classes.Length)];
}

string GetItemObject(InventoryView item)
{
    var name = item.Name.Replace("'", string.Empty).Replace(",", string.Empty);
    var price = item.Price.ToString("N4");
    var code = item.Code;
    var inventoryId = item.InventoryId;
    return "{\"Name\":\"" + name
        + "\",\"Price\":\"" + price
        + "\",\"Code\":\"" + code
        + "\",\"InventoryId\":\"" + inventoryId
        + "\"}";
}

}

<div class="row">
    <!-- column -->
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Sales</h4>
                <h6 class="card-subtitle">Make a sale to a customer :)</h6>
                <partial name="_Flash" />

                <div class="row">
                    <div class="col-sm-8 offset-md-2">
                        <div class="row">
                            <div class="col-sm-12">

                                <table class="table inventorySales">
                                    <thead>
                                        <tr>
                                            <th>Code</th>
                                            <th>Item</th>
                                            <th class="text-center">Quantity</th>
                                            <th class="text-right">Price (@Defaults.CountryProfile.Currency)</th>
                                            <th class="text-right">Sub Total (@Defaults.CountryProfile.Currency)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Sales)
                                        {
                                            //var itemTotal = item.Price * item.Quantity;
                                            subTotal += item.Total;
                                            <tr class="inventoryItem">
                                                <td>@item.Code</td>
                                                <td>@item.Name</td>
                                                <td class="text-center">
                                                    @item.Quantity
                                                </td>
                                                <td class="text-right">@item.Price.ToString("N4")</td>
                                                <td class="text-right">@item.Total.ToString("N4")</td>
                                            </tr>
                                        }

                                        <tr id="trAdd" class="totals">
                                            <td colspan="4" class="text-right">Sub Total (@Defaults.CountryProfile.Currency)</td>
                                            <td class="text-right" id="trSubTotal">@subTotal.ToString("N4")</td>
                                        </tr>
                                        <tr class="totals">
                                            <td colspan="4" class="text-right font-weight-bold">Total (@Defaults.CountryProfile.Currency)</td>
                                            <td class="text-right font-weight-bold">@subTotal.ToString("N4")</td>
                                        </tr>
                                        <tr class="totals">
                                            <td colspan="4" class="text-right font-weight-bold">Enter Amount</td>
                                            <td class="text-right font-weight-bold">
                                                <input type="text" class="form-control" id="Amount" onkeypress="return isNumberKey(event)" autocomplete="off" />
                                            </td>
                                        </tr>
                                        <tr class="totals">
                                            <td colspan="4" class="text-right font-weight-bold">Change</td>
                                            <td class="text-right font-weight-bold" id="trChange"></td>
                                        </tr>
                                        <tr class="totals">
                                            <td class="text-right" colspan="5">
                                                <button type="button" class="btn btn-secondary" id="inventoryBack">&laquo; Cancel</button>
                                                &nbsp;&nbsp;&nbsp;&nbsp;
                                                @*<button type="button" class="btn btn-danger" id="inventoryCancel">Cancel</button>
                                                &nbsp;&nbsp;&nbsp;&nbsp;*@
                                                <button type="button" class="btn btn-success" id="inventoryPay" 
                                                        onclick="modalConfirmPay(this)">
                                                    Pay & Print Receipt
                                                </button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>


                            </div>


                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<form asp-page="Pay" asp-page-handler="ProcessTransaction" method="post" id="inventorySale">
    <input type="hidden" name="Items" value="@JsonConvert.SerializeObject(Model.Sales.Select(c => new { c.InventoryId, c.Quantity, c.InventoryStockId }).ToList())" />
    <input type="hidden" name="AmountPaid" id="AmountPaid" />
</form>
@section scriptsBottom{
    <div class="modal fade" id="confirmPayModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel1">Processing Payments</h4>
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>*@
                </div>
                <div class="modal-body text-center" style="padding-left: 180px;">
                    <div class="salesloader"></div>
                </div>
                <div class="modal-footer">
                    @*<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <a href="" id="modDelete" class="btn btn-primary">YES DELETE</a>*@
                </div>
            </div>
        </div>
    </div>
    @*<script src="/js/jquery.sweet-alert.custom.js"></script>*@
    <script>
        var subTotal = parseFloat(@subTotal.ToString("N4"));

        function isNumberKey(evt) {
            var charCode = (evt.which) ? evt.which : evt.keyCode;
            if (charCode != 46 && charCode > 31
                && (charCode < 48 || charCode > 57))
                return false;
            return true;
        }

        $(document).ready(function() {

            
            $('#Amount').focusout(function() {
                $('#trChange').text('');
                //$('#Stock_Quantity').val(prevQty + newQty);
                var amount = parseFloat($(this).val());
                if (amount > 0 && amount >= subTotal) {
                    var change = amount - subTotal;
                    if (change > 0) {
                        $('#trChange').text(change.toFixed(4));
                        //$('#Stock_Quantity').val(prevQty + newQty);
                    }

                }
            });

            $('#inventoryBack').click(function(){
                swal({   
                    title: "Are you sure?",   
                    text: "This sale will be cancelled",   
                    type: "warning",   
                    showCancelButton: true,   
                    confirmButtonColor: "#DD6B55",   
                    confirmButtonText: "Yes, cancel it!",   
                    closeOnConfirm: false 
                },function(){   
                    window.location = "/sales"
                });
            });
        });

        function modalConfirmPay(e) {

            if ($("#Amount").val() === "") {
                swal({
                    title: "Amount not valid",
                    text: "Please enter a valid amount",
                    type: "warning"
                });
                return;
            }
            var amount = parseFloat($("#Amount").val());

            if (amount < subTotal) {
                swal({
                    title: "Amount not valid",
                    text: "Please enter a valid amount",
                    type: "warning"
                });
            } else {
                $("#AmountPaid").val(amount);
                $('#confirmPayModal').modal({ backdrop: 'static', keyboard: false });
                $('#inventorySale').submit();
            }

            

            //var modal = $('#deleteModal');
            //modal.find('#modContent').text('Delete Category ' + name);
            //modal.find('#modDelete').attr('href', '/admin/inventory/category?handler=delete&id=' + id);

            
        }

    </script>
}

StoreLedger/Pages/Sales/Receipts.cshtml
@page
@using StoreLedger.Model
@using StoreLedger.Model.Repos
@using StoreLedger.Models
@model StoreLedger.Pages.Sales.ReceiptsModel
@inject TransactionRepo TransactionRepo
@{
    ViewData["Title"] = "Receipts";
    var trans = Model.TransactionItems
        .OrderByDescending(c => c.DateCreated)
        .Select(c => c.TransactionId)
        .Distinct();

    var total = Model.TransactionItems.Sum(c => c.Total);
}

@functions
{

    string GetUser(Transaction trans)
    {
        var user = Model.Users.FirstOrDefault(c => c.UserId == trans.Userid);

        if (user == null)
        {
            return string.Empty;
        }

        return $"{user.FirstName} {user.LastName}";
    }

    string GetInventory(IEnumerable<Inventory> inventories, Guid inventoryId)
    {
        var item = inventories.FirstOrDefault(c => c.InventoryId == inventoryId);
        return item != null ? item.Name : string.Empty;
    }



}
@section scripts{
    <!-- Date picker plugins css -->
    <link href="/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker plugins css -->
    <link href="/assets/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet">
    <link href="/assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
}

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Receipts for @Model.CurrentDate.ToString("dd-MMMM-yyyy")</h4>
                                <div class="text-right">
                                    
                                </div>
                                <div class="text-right m-t-10">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="input-group p-t-40">
                            <input type="text" class="form-control mydatepicker" placeholder="mm/dd/yyyy" id="date">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="icon-calender"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <button type="button" class="btn btn-secondary" id="btnSearch">Search</button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="text-right">

                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        @{
                            var counter = trans.Count();
                        }
                        @foreach (var tranId in trans)
                        {
                            var parentTrans = TransactionRepo.FindAsync(tranId).Result;
                            
                        <table class="table border-bottom">

                            <tr>
                                <td colspan="4">
                                    <span class="badge badge-category">Sale # @counter</span>
                                    <span class="badge badge-attendant">Attendant: @GetUser(parentTrans)</span>
                                </td>
                                <td class="text-right"></td>
                                <td class="text-right"></td>
                            </tr>
                            <tr>
                                <th class="rpColDate">Date</th>
                                <th class="rpColItem">Item</th>
                                <th class="rpColQty text-center">Quantity</th>
                                <th class="rpColPrice text-right">Price (@Defaults.CountryProfile.Currency)</th>
                                <th class="rpColTotal text-right">Total (@Defaults.CountryProfile.Currency)</th>
                                <td class="text-right"></td>
                            </tr>

                            @{
                                counter--;
                                var transItems = Model.TransactionItems.Where(c => c.TransactionId == tranId);
                            }
                            @foreach (var item in transItems)
                            {

                                <tr>
                                    <td>
                                        @item.DateCreated.ToString("dd-MMM-yyyy HH:mm")
                                    </td>
                                    <td>@GetInventory(Model.Inventories, item.InventoryId)</td>
                                    <td class="text-center">@item.Quantity</td>
                                    <td class="text-right">@item.Price.ToString("N4")</td>
                                    <td class="text-right">
                                        @item.Total.ToString("N4")
                                    </td>
                                    <td></td>
                                </tr>
                            }
                                <tr>
                                    <td colspan="3" class="text-left text-primary">
                                        <div class="badge badge-secondary text-left">
                                            Amount Paid: @Defaults.CountryProfile.Currency @parentTrans.AmountPaid.ToString("N4")<br />
                                            Change : @Defaults.CountryProfile.Currency @parentTrans.AmountChange.ToString("N4")
                                        </div>
                                    </td>
                                    <td class="text-right  font-weight-bold">Total</td>
                                    <td class="text-right  font-weight-bold">@transItems.Sum(c => c.Total).ToString("N4")</td>
                                </tr>
                        </table>
                        <div class="m-b-30"></div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scriptsBottom{
    <!-- Date Picker Plugin JavaScript -->
    <script src="/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <!-- Date range Plugin JavaScript -->
    <script src="/assets/plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>

    <script src="~/js/exportTable/xlsx.full.min.js"></script>
    <script src="/js/exportTable/FileSaver.min.js"></script>
    <script src="/js/exportTable/tableexport.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.mydatepicker, #datepicker').datepicker({
                format: 'mm/dd/yyyy'
            });

            $('#btnSearch').click(function () {
                var date = $("#date").val();
                if (date !== "")
                    window.location = "/sales/receipts?currdate=" + date;
                else {
                    swal({
                        title: "Cannot Search",
                        text: 'Select a date',
                        type: "warning"
                    });
                }
            });

            $('#btnDownload').click(function () {
                $(".exportData").tableExport({
                    formats: ['xlsx', 'csv', 'txt'],
                    filename: 'Daily_Report_@DateTime.Now.ToString("yy-MM-dd-HH-mm")'
                });
            });


        });
    </script>
}