StoreLedger/Pages/Admin/Users/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreLedger.Activities;
using StoreLedger.Model;
using StoreLedger.Model.Repos;
using StoreLedger.Models;

namespace StoreLedger.Pages.Admin.Users
{
    [Authorize(Roles = Defaults.Role.AllAdmin)]
    public class AdminUsersPage : BasePageModel
    {
        private readonly UserRepo _userRepo;
        private readonly UserRoleRepo _userRoleRepo;
        private readonly UserActivity _userActivity;

        public AdminUsersPage(UserRepo userRepo, UserRoleRepo userRoleRepo, UserActivity userActivity)
        {
            _userRepo = userRepo;
            _userRoleRepo = userRoleRepo;
            _userActivity = userActivity;
            Users = new List<User>();
        }

        public string Message { get; set; }
        public SelectList Roles { get; set; }

        public List<User> Users { get; set; }


        public async Task OnGetAsync()
        {
            Users = await _userRepo.GetAsync(c => c.UserId != 1, c => c.UserRole);
        }

        public async Task<IActionResult> OnGetDeleteAsync(int id)
        {
            var results = await _userActivity.Delete(HttpContext.User.Identity.Name, id);
            if(!results.IsSuccessful)
                FlashError(results.Message);
            else
                FlashSuccess("User Deleted");

            return RedirectToPage("./index");
        }
    }
}

StoreLedger/Pages/Admin/Users/UsersForm.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreLedger.Activities;
using StoreLedger.Model;
using StoreLedger.Model.Repos;
using StoreLedger.Models;

namespace StoreLedger.Pages.Admin.Users
{
    [Authorize]
    public class AdminUsersForm : BasePageModel
    {
        private readonly UserRepo _userRepo;
        private readonly UserRoleRepo _userRoleRepo;
        private readonly UserActivity _userActivity;

        public SelectList Roles { get; set; }
        public SelectList StatusOption { get; set; }
        public PageForm PageForm { get; set; }

        [BindProperty]
        public User AppUser { get; set; }

        public AdminUsersForm(UserRepo userRepo, UserRoleRepo userRoleRepo, UserActivity userActivity)
        {
            _userRepo = userRepo;
            _userRoleRepo = userRoleRepo;
            _userActivity = userActivity;
            StatusOption = new SelectList((new[]
                {
                    new {Value = true, Name = "Yes"},
                    new {Value = false, Name = "No"}
                }),
                "Value",
                "Name",
                0
            );
            AppUser = new User{ UserId = 0};
        }

        public ActionResult OnGet()
        {
            return RedirectToPage("./index");
        }

        public async Task OnGetCreateAsync()
        {

            PageForm = new PageForm("Add A User","create");
            var roles = await _userRoleRepo.GetAsync(c => c.RoleId != Defaults.Role.SuperAdminId);
            Roles = new SelectList(roles.AsEnumerable(), "RoleId", "Name");
        }

        public async Task<IActionResult> OnPostCreateAsync()
        {
            PageForm = new PageForm("Add A User", "create");

            if (ModelState.IsValid)
            {
                var results = await _userActivity.Create(AppUser);
                if (!results.IsSuccessful)
                {
                    FlashWarning(results.Message);
                    return Page();
                }
                FlashSuccess(results.Message);
            }

            return RedirectToPage("./index");
        }

        public async Task OnGetEditAsync(int id)
        {
            PageForm = new PageForm("Edit A User", "edit");
            AppUser = await _userRepo.FindAsync(id);
            var roles = await _userRoleRepo.GetAsync(c => c.RoleId != Defaults.Role.SuperAdminId);
            Roles = new SelectList(roles.AsEnumerable(), "RoleId", "Name");
        }

        public async Task<IActionResult> OnPostEditAsync()
        {
            PageForm = new PageForm("Edit A User", "edit");
            if (ModelState.IsValid)
            {
                var results = await _userActivity.Edit(AppUser);
                if (!results.IsSuccessful)
                {
                    FlashWarning(results.Message);
                    return Page();
                }
                FlashSuccess(results.Message);
            }

            return RedirectToPage("./index");
        }
    }
}

StoreLedger/Pages/Admin/Users/Index.cshtml
@page
@using StoreLedger.Model
@using StoreLedger.Pages.Admin
@using StoreLedger.Pages.Admin.Users
@model StoreLedger.Pages.Admin.Users.AdminUsersPage
@{
    ViewData["Title"] = "Users";
}
@functions
{

    string SetRoleLabel(string role)
    {
        if (role == Defaults.Role.SuperAdministrator) return "label-primary";
        if (role == Defaults.Role.Administrator) return "label-success";
        if (role == Defaults.Role.Manager) return "label-info";
        if (role == Defaults.Role.Attendant) return "label-danger";

        return "label-primary";
    }

}
<div class="row">
    <!-- column -->
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Users</h4>
                <h6 class="card-subtitle">User management</h6>
                <partial name="_Flash" />
                <div class="button-group text-right">
                    <a asp-page="usersform" asp-page-handler="create" class="btn btn-secondary">
                        <i class="mdi mdi-account-plus"></i>
                        Add User
                    </a>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Role</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Mobile Number</th>
                                <th>Username</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model.Users)
                        {
                            var roleClass = "label-success";
                            var role = item.UserRole.Name;
                            <tr>
                                <td><span class="label @SetRoleLabel(role)">@item.UserRole.Name</span> </td>
                                <td>@item.FirstName</td>
                                <td>@item.LastName</td>
                                <td>@item.MobileNumber</td>
                                <td>@item.Username</td>
                                <th class="text-right">
                                    <a asp-page="Usersform" asp-page-handler="edit" asp-route-id="@item.UserId" class="btn btn-outline-secondary">Edit</a>
                                    &nbsp;&nbsp;
                                    <a href="#"
                                       class="btn btn-outline-danger deleteUser" 
                                       data-toggle="modal" data-target="#deleteModal"
                                       data-id="@item.UserId" data-name="@item.FirstName" onclick="modalFunc(this)">Delete</a>
                                </th>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</div>

@section scriptsBottom
{
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel1">New message</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body">
                    <span id="modContent"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a href="" id="modDelete" class="btn btn-primary">YES DELETE</a>
                </div>
            </div>
        </div>
    </div>
    <script>
            //$('.deleteUser').on('show.bs.modal',
            //    function(e) {
            //        var id = $(e.relatedTarget).attr('data-id');
            //        var name = $(e.relatedTarget).attr('data-name');

            //        var modal = $(this);
            //        modal.find('#modContent').text('Delete User ' + name);
            //        modal.find('#modDelete').attr('asp-route-id', id);
            //});

        function modalFunc(e) {
            var id = $(e).attr('data-id');
            var name = $(e).attr('data-name');

            var modal = $('#deleteModal');
            modal.find('#modContent').text('Delete User ' + name);
            modal.find('#modDelete').attr('href', '/admin/users?handler=delete&id=' + id);
        }
                
    </script>
}

StoreLedger/Pages/Admin/Users/UsersForm.cshtml
@page
@using StoreLedger.Pages.Admin
@using StoreLedger.Pages.Admin.Users
@model StoreLedger.Pages.Admin.Users.AdminUsersForm
@{
    ViewData["Title"] = $"Users : ";
}
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <h3 class="box-title m-b-0">@Model.PageForm.Title</h3>
            <p class="text-muted m-b-30 font-13"> &nbsp; </p>
            <partial name="_Flash" />
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <form asp-page-handler="@Model.PageForm.Method" method="post">
                        <input type="hidden" asp-for="AppUser.UserId"/>
                        <div class="form-group">
                            <label asp-for="AppUser.FirstName">First Name</label>
                            <input type="text" required class="form-control" asp-for="AppUser.FirstName" id="FirstName" asp placeholder="Enter First Name">
                            <span asp-validation-for="AppUser.FirstName"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AppUser.LastName">Last Name</label>
                            <input type="text" required asp-for="AppUser.LastName" class="form-control" id="LastName" placeholder="Enter Last Name">
                            <span asp-validation-for="AppUser.LastName"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AppUser.MobileNumber">Mobile Number</label>
                            <input type="text" required asp-for="AppUser.MobileNumber" class="form-control" id="MobileNumber" placeholder="Enter Last Mobile Number">
                            <span asp-validation-for="AppUser.MobileNumber"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AppUser.RoleId">Role</label>
                            <select required asp-for="AppUser.RoleId" asp-items="@Model.Roles" class="form-control">
                                <option value="">Pick one</option>
                            </select>
                            <span asp-validation-for="AppUser.RoleId"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AppUser.IsEnabled">Enabled</label>
                            <select asp-for="AppUser.IsEnabled" asp-items="@Model.StatusOption" class="form-control"></select>
                        </div>
                        <div class="form-group">
                            <label asp-for="AppUser.Username">Username</label>
                            <input type="text" required asp-for="AppUser.Username" class="form-control" id="Username" placeholder="Enter Username" maxlength="10">
                            <small>10 characters max</small>
                            <span asp-validation-for="AppUser.Username"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AppUser.Password">Password</label>
                            <input type="text" required asp-for="AppUser.Password" class="form-control" id="Password" placeholder="Enter Password" maxlength="10">
                            <small>10 characters max</small>
                            <span asp-validation-for="AppUser.Password"></span>
                        </div>
                        <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                        <a href="/admin/users" class="btn btn-inverse waves-effect waves-light">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>