StoreLedger/Models/Flash.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;

namespace StoreLedger.Models
{
    public class Flash
    {

        public const string SessionKey = "flash";

        public static void FlashWarning(string message, HttpContext context)
        {
            var flashMessage = new Message
            {
                Type = MessageTypes.Warning,
                Body = message.Trim()
            };

            PersistMessage(flashMessage, context);
        }

        public static void FlashSuccess(string message, HttpContext context)
        {
            var flashMessage = new Message
            {
                Type = MessageTypes.Success,
                Body = message.Trim()
            };

            PersistMessage(flashMessage, context);
        }
        
        public static void FlashError(string message, HttpContext context)
        {
            var flashMessage = new Message
            {
                Type = MessageTypes.Error,
                Body = message.Trim()
            };

            PersistMessage(flashMessage, context);
        }

        private static void PersistMessage(Message flashMessage, HttpContext context)
        {
            context.Session.SetString(SessionKey, JsonConvert.SerializeObject(flashMessage));
        }
    }

    public class Message
    {
        public string Type { get; set; }
        public string Body { get; set; }
        public bool Dismissible { get; set; }
        public Message()
        {
            Dismissible = true;
        }
    }

    public class MessageTypes
    {
        public const string Success = "alert-success";
        public const string Warning = "alert-warning";
        public const string Error = "alert-danger";
    }

}

StoreLedger/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreLedger.Activities;
using StoreLedger.Models;
using StoreLedger.Models.ViewModels;

namespace StoreLedger.Pages
{
    public class LoginModel : BasePageModel
    {
        private readonly LoginActivity _loginActivity;

        public LoginModel(LoginActivity loginActivity)
        {
            _loginActivity = loginActivity;
        }

        [BindProperty]
        public LoginViewModel Login { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnGetLogoutAsync()
        {
            HttpContext.Session.Clear();
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToPage("/login");
        }

        public async Task<IActionResult> OnPostLoginAsync()
        {
            var results = await _loginActivity.Login(HttpContext, Login.Username, Login.Password);

            if(!results.IsSuccessful)
                FlashError(results.Message);
            
            return RedirectToPage("/index");
        }
    }
}

StoreLedger/Pages/Shared/_Flash.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity.UI.Pages.Account.Manage.Internal
@using Newtonsoft.Json
@using StoreLedger.Models
@{
    var message = Context.Session.GetString("FlashMsg");// TempData[Flash.SessionKey] as string;TempData["flash"]; //

    Message objMsg = null;
    if (!string.IsNullOrEmpty(message))
    {
        objMsg = JsonConvert.DeserializeObject<Message>(message);
    }

    Context.Session.SetString("FlashMsg", string.Empty);
}

@if (objMsg != null)
{
    <div class="alert @objMsg.Type">
        @Html.Raw(objMsg.Body)
    </div>
}

StoreLedger/Pages/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopLedger</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">ShopLedger</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ShopLedger</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

StoreLedger/Pages/Shared/_Layout.cshtml
@using System
@using System.Linq
@using System.Net
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
@using StoreLedger.Model

@{
    var url = Context.Request.Path.Value.ToLower(); // /admin/users
    var userFullName = Context.User.Claims.FirstOrDefault(c => c.Type == Defaults.RoleType.FullName);
    var roleName = Context.User.Claims.FirstOrDefault(c => c.Type == Defaults.RoleType.RoleName);
    
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon.png">
    <title>Store Ledger - @ViewData["Title"]</title>
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    @if (url.StartsWith("/admin"))
    {
        <link href="/css/colors/blue-dark.css" id="theme" rel="stylesheet">
    }
    else
    {
        <link href="/css/colors/blue.css" id="theme" rel="stylesheet">
    }

    <link href="/css/custom.css" id="theme" rel="stylesheet">
    <link href="/assets/plugins/sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("scripts", false)
</head>
<body class="fix-header card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    @*<div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>*@
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">
                        <!-- Logo icon -->
                        <b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                            <!-- Light Logo icon -->
                            <img src="/icons/icon-monitor.png" alt="homepage" class="light-logo" />
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span>
                            <!-- dark Logo text -->
                            <img src="/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                            <!-- Light Logo text -->
                            @*<img src="/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />*@
                            <span class="logoName">Store Ledger</span>
                            
                        </span>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto mt-md-0 ">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                        <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="icon-arrow-left-circle"></i></a> </li>
                        <!-- ============================================================== -->
                        <!-- Comment -->
                        <!-- ============================================================== -->
                    </ul>
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="/assets/images/user.png" alt="user" class="profile-pic" />
                            </a>
                            <div class="dropdown-menu dropdown-menu-right animated flipInY">
                                <ul class="dropdown-user">
                                    <li>
                                        <div class="dw-user-box">
                                            <div class="u-img"><img src="/assets/images/user.png" alt="user"></div>
                                            <div class="u-text">
                                                <h4>@userFullName?.Value</h4>
                                                <span class="text-danger">@roleName?.Value</span>
                                            </div>
                                        </div>
                                    </li>
                                    @*<li role="separator" class="divider"></li>
                                    <li><a href="#"><i class="ti-user"></i> My Profile</a></li>
                                    <li><a href="#"><i class="ti-wallet"></i> My Balance</a></li>
                                    <li><a href="#"><i class="ti-email"></i> Inbox</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
                                    <li role="separator" class="divider"></li>*@
                                    <li><a asp-page="/login" asp-page-handler="logout"><i class="fa fa-power-off"></i> Logout</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        @if (url.StartsWith("/admin"))
        {
            <partial name="_menubarAdmin" />
        }
        else
        {
            <partial name="_menubar" />
        }

        <div class="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <footer class="footer">
                © @DateTime.Today.Year Store Ledger
            </footer>
        </div>
    </div>
    <script src="/assets/plugins/jquery/jquery.min.js"></script>
    <script src="/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/js/jquery.slimscroll.js"></script>
    <script src="/js/waves.js"></script>
    <script src="/js/sidebarmenu.js"></script>
<script src="/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
<script src="/assets/plugins/sweetalert/sweetalert.min.js"></script>
<script src="/js/custom.min.js"></script>

    @RenderSection("scriptsBottom", false)
</body>
</html>